negative_responses = [
    f"A sentence like '{{text}}' carries a negative tone. It might imply disappointment or dissatisfaction.",
    "From the structure and word choices, this message sounds unpleasant. There is a sense of discomfort in it.",
    "These words seem to reflect feelings of disappointment or anger. The negative nuance is quite strong.",
    f"'{{text}}' has an unpleasant connotation. This sentence contains a negative expression.",
    "This message seems to come from a place of frustration. A sentence like this can indicate dissatisfaction.",
    f"By stating '{{text}}', you might be expressing disappointment. This sentence has a negative tone.",
    "This sentence shows dissatisfaction or criticism. Its emotional tone feels negative.",
    "Emotionally, this message doesn’t bring comfort. There’s a strong sense of negativity in it.",
    f"I sense displeasure from the sentence '{{text}}'. Maybe you're trying to express criticism or disappointment.",
    "This sentence sounds like an outburst of dissatisfaction. There is a negative nuance in its delivery.",
    "The tone in this sentence sounds cold and pressing. It shows an unpleasant emotional state.",
    "You might have been upset when writing this. The sentence is full of negative emotional pressure.",
    f"'{{text}}' gives an unpleasant impression. This sentence expresses dissatisfaction.",
    "There is an element of rejection or criticism in this sentence. The negative tone is quite apparent.",
    "This sentence contains emotional tension. You might be feeling frustrated or disappointed.",
    "Your expression in this sentence feels heavy. It shows an emotional burden.",
    f"From '{{text}}', it seems you’re going through something unpleasant.",
    "The tone coming from this sentence is unfriendly. There’s a sense of anger or displeasure.",
    "This sentence isn’t the kind that brings comfort. It tends to express annoyance.",
    "The expression is firm, but the emotional tone isn’t positive. Maybe you're feeling disturbed.",
    f"'{{text}}' indicates rejection or discomfort. This message has a negative nuance.",
    "This message contains a strong form of dissatisfaction. The emotion feels heavy.",
    "I sense disappointment in this sentence. The negative tone is quite clear.",
    f"From the sentence '{{text}}', it seems like you’re not happy about something.",
    "This response sounds cynical or sarcastic. It's usually used when feeling upset.",
    f"The words in '{{text}}' reflect dissatisfaction. This is a negative response.",
    "The tone of this sentence is harsh and lacks empathy. Its negative impression is strong.",
    "Language like this is usually used in contexts of criticism or complaints. This is not a positive sentence.",
    "This sentence shows frustration or annoyance. It’s strongly felt from the word choices.",
    f"'{{text}}' shows that you might be unhappy with something.",
    "This message implies a feeling of pressure. A sentence like this can affect the reader.",
    "The negative tone dominates this sentence. Maybe you're trying to let out some feelings.",
    f"I think the sentence '{{text}}' contains a form of rejection. Quite emotional and negative.",
    "Your words might be honest, but the tone is unpleasant. This sentence sounds negative.",
    f"'{{text}}' tends to show sharp criticism. This message isn’t constructive.",
    "This response has a negative tone and tends to be accusatory. The word choices are strong.",
    "This sentence sounds pessimistic. Maybe there’s a burden you’re feeling.",
    f"'{{text}}' might be an unspoken complaint. It comes across as heavy.",
    "The tone of this sentence feels like resistance. There’s no positive spirit in it.",
    "The expression is strong but negative. Seems like you’re feeling fed up.",
    "A sentence like this may reflect a bad mood.",
    f"'{{text}}' contains a harsh and bitter message. This sentence is full of negative emotion.",
    "This is a sentence that expresses disappointment or emotional pain.",
    f"You sound upset while writing '{{text}}'. This sentence isn’t pleasant.",
    "This sentence creates a heavy atmosphere. The negative nuance is strongly felt.",
    f"From the words '{{text}}', you seem dissatisfied with something.",
    "This negative emotional tone is quite noticeable. Maybe something is bothering you.",
    "This response feels like a heartfelt outpouring. The sentence sounds heavy.",
    f"I sense anger from '{{text}}'. This sentence is quite harsh.",
    "This sentence doesn’t sound friendly. You might be under pressure.",
    "This message conveys discomfort. The sentence carries a deep negative impression."
]

positive_responses = [
    f"A sentence like '{{text}}' shows a very positive aura. The words give off a sense of optimism and enthusiasm.",
    f"Hmm, from words like '{{text}}', it seems you're in a good mood. That sentence sounds very pleasant.",
    "Your response reflects a positive feeling. An optimistic tone and encouragement are clearly felt in it.",
    "This sentence contains uplifting spirit and energy. It’s clear that you’re trying to express something good.",
    f"'{{text}}' sounds like a compliment or a sincere form of appreciation. It’s clearly a positive expression.",
    "The sentence you typed carries many positive meanings. Very fitting as a motivational boost.",
    "This message sounds very uplifting. You might be feeling enthusiastic or trying to motivate others.",
    f"From words like '{{text}}', I can sense that it’s a form of support or appreciation. A very positive sentence.",
    "You’re expressing something with great enthusiasm. This sentence has a strong positive vibe.",
    "This sentence is suitable as a motivational quote. The tone and word choice are full of hope.",
    f"I like the way you wrote '{{text}}'. That sentence inspires and shows optimism.",
    "This is a positive expression. It can brighten someone’s day.",
    "Emotionally, this sentence reflects joy. Full of meaning and energy.",
    f"'{{text}}' clearly shows that you like something. It feels warm and sincere.",
    "The tone of this sentence is very friendly and uplifting. Perfect for encouraging someone.",
    f"With words like '{{text}}', you’re delivering a very joyful message.",
    "This sentence conveys feelings of happiness and gratitude. A clear sign of a positive expression.",
    "You’ve successfully shared a cheerful message. This sentence improves the mood.",
    f"'{{text}}' gives a very supportive impression. A sentence like this could make someone smile.",
    "The word choice and structure reflect a happy state of mind. Very positive!",
    "This message carries hope and motivation. Great for encouraging someone.",
    f"A sentence like '{{text}}' can make someone’s day better. A wonderful expression of positivity.",
    "The tone in this sentence is very uplifting. It gives a sense of optimism and peace.",
    f"'{{text}}' is a delightful form of communication. Its positive energy is felt.",
    "This sentence is perfect to start the day with enthusiasm. The positive tone is clear.",
    f"I can sense good intentions in words like '{{text}}'. A positive and touching message.",
    "Language like this is often used when giving encouragement. Truly a positive sentence.",
    "You’re expressing joyful emotions. The words feel warm and calming.",
    f"'{{text}}' could be a form of support or satisfaction about something. The nuance is very positive.",
    "This is the kind of sentence that lifts spirits. It feels very uplifting.",
    f"The word choice in '{{text}}' shows joy. This sentence is emotionally positive.",
    "A sentence like this is great when trying to motivate others. The positive tone is strong.",
    f"'{{text}}' feels like a form of appreciation. Very positive and pleasant.",
    "The optimistic tone is clearly visible. This sentence spreads enthusiasm.",
    "Are you in a good mood? This sentence is very uplifting.",
    f"'{{text}}' implies feelings of satisfaction or happiness. Very positive and convincing.",
    "This sentence sounds very supportive. It boosts confidence.",
    "Language like this is widely used in positive communication. Very fitting as encouragement.",
    f"I like the positive energy from '{{text}}'. This sentence has a good impact.",
    "This type of sentence usually lifts others up. Very positive and encouraging.",
    f"From the sentence '{{text}}', it’s clear that you’re expressing appreciation. Very positive!",
    "This sentence is an expression that boosts motivation. The word choice is excellent.",
    "This message gives a strong push. Perfect for a hopeful moment.",
    f"'{{text}}' brings a happy and peaceful nuance. A warm, positive sentence.",
    "This kind of sentence is perfect in constructive communication. Very positive.",
    "The tone of the writing feels warm and full of spirit. A delightful expression.",
    f"You used uplifting words in '{{text}}'. Very well done!",
    "This sentence can be a morale booster for its reader. Positive and memorable.",
    f"From the words '{{text}}', the spirit and optimism are strongly felt.",
    "Overall, this is a positive sentence that can warm someone's heart."
]
